name: Build Linux Packages

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            cmake \
            freeglut3-dev \
            libglu1-mesa-dev \
            mesa-common-dev \
            rpm \
            wget \
            fuse

      - name: Configure
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build

      - name: Package deb rpm
        run: |
          cd build
          cpack

      - name: Build AppImage
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage

          mkdir -p AppDir/usr/bin
          cp bin/main AppDir/usr/bin/

          ./linuxdeploy-x86_64.AppImage \
            --appdir AppDir \
            --executable AppDir/usr/bin/main \
            --desktop-file resource/maze.desktop \
            --icon-file resource/maze.png \
            --output appimage

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-packages
          path: |
            build/*.deb
            build/*.rpm
            *.AppImage